INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`, `activity`, `subtype`) VALUES
('Service_Lines', 'adult', 'Adult', 0, 0, 0, '', 'dental', '', 0, 0, 0, ''),
('Service_Lines', 'ancillary', 'Ancillary / Non-Provider', 0, 0, 0, '', 'medical|behave', '', 0, 0, 1, ''),
('Service_Lines', 'behave', 'Behavioral Health', 0, 0, 0, '', 'behave', '', 0, 0, 0, ''),
('Service_Lines', 'care', 'Care Coordination', 0, 0, 0, '', 'vbc|behave', '', 0, 0, 1, ''),
('Service_Lines', 'care_home', 'Care Coordination, @ Home', 0, 0, 0, '', 'vbc', '', 0, 0, 1, ''),
('Service_Lines', 'cli_rx', 'Clinical Pharmacy', 0, 0, 0, '', 'pharma', '', 0, 0, 1, ''),
('Service_Lines', 'cprit_nav', 'Cprit Navigator', 0, 0, 0, '', 'Medical', '', 0, 0, 1, ''),
('Service_Lines', 'crisis', 'Crisis', 0, 0, 0, '', '', '', 0, 0, 1, ''),
('Service_Lines', 'dental', 'Dental', 0, 0, 0, '', 'dental', '', 0, 0, 0, ''),
('Service_Lines', 'enroll', 'Enrollment / Eligibility', 0, 0, 0, '', 'enroll', '', 0, 0, 1, ''),
('Service_Lines', 'event', 'Events', 0, 0, 0, '', 'medical', '', 0, 0, 0, ''),
('Service_Lines', 'funcmed', 'Functional Medicine', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'im', 'Internal Medicine', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'image', 'Imaging', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'infusion', 'Infusion', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'medical', 'Medical', 0, 0, 0, '', 'medical|behave', '', 0, 0, 0, ''),
('Service_Lines', 'men', 'Men\'s Health', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'none', '- Choose a Category -', 0, 0, 0, '', '', '', 0, 0, 0, ''),
('Service_Lines', 'pediatric', 'Pediatrics', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'pharmacy', 'Pharmacy', 0, 0, 0, '', 'pharma', '', 0, 0, 0, ''),
('Service_Lines', 'primary', 'Primary Care', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'psych', 'Psychiatry', 0, 0, 0, '', 'behave', 'bh_term', 0, 0, 1, ''),
('Service_Lines', 'referral', 'Referral Management', 0, 0, 0, '', 'vbc', '', 0, 0, 1, ''),
('Service_Lines', 'research', 'Research', 0, 0, 0, '', 'research', '', 0, 0, 0, ''),
('Service_Lines', 'special', 'Specialty', 0, 0, 0, '', 'medical', '', 0, 0, 1, ''),
('Service_Lines', 'therapy', 'Therapy', 0, 0, 0, '', 'behave', 'bh_term', 0, 0, 1, ''),
('Service_Lines', 'transition', 'Transitional Care', 0, 0, 0, '', 'medical|behave|vbc', '', 0, 0, 1, ''),
('Service_Lines', 'vbc', 'VBC', 0, 0, 0, '', 'medical|behave', '', 0, 0, 0, ''),
('Service_Lines', 'women', 'Women\'s Health', 0, 0, 0, '', 'medical', '', 0, 0, 1, '');
